name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: buildfile
      run: npm run build --if-present

    - name: Run Jest Tests
      run: npm test
